// <auto-generated />
using System;
using GarlandHouse.DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HouseGarland.DataModel.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20241123145211_AddOrderAndIsFavorite")]
    partial class AddOrderAndIsFavorite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GarlandHouse.DataModel.Entity.FileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("FileEntities");
                });

            modelBuilder.Entity("GarlandHouse.DataModel.Entity.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContractNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerFIO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LinkToAmoCRM")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LinkToYandexMap")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MeasurementComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("MeasurementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaymentMethodForMeasurement")
                        .HasColumnType("integer");

                    b.Property<int>("PriceForMeasurement")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GarlandHouse.DataModel.Entity.OrderObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("VersionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VersionId");

                    b.ToTable("OrderObjects");
                });

            modelBuilder.Entity("GarlandHouse.DataModel.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FIO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GarlandHouse.DataModel.Entity.UserOrder", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("UserOrder");
                });

            modelBuilder.Entity("GarlandHouse.DataModel.Entity.Version", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Budget")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<bool>("isFavorite")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Versions");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CommentDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.BeltLight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CableColor")
                        .HasColumnType("integer");

                    b.Property<int>("Contours")
                        .HasColumnType("integer");

                    b.Property<int>("GlowShade")
                        .HasColumnType("integer");

                    b.Property<int>("LampStep")
                        .HasColumnType("integer");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("OrderObjectId")
                        .HasColumnType("integer");

                    b.Property<int>("PvsLength")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderObjectId");

                    b.ToTable("BeltLights");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.BoxPvsCabel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Color")
                        .HasColumnType("integer");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("OrderObjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderObjectId");

                    b.ToTable("BoxPvsCabels");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.Corrugation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CableColor")
                        .HasColumnType("integer");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("OrderObjectId")
                        .HasColumnType("integer");

                    b.Property<int>("Thickness")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderObjectId");

                    b.ToTable("Corrugations");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.Curtain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Bracing")
                        .HasColumnType("integer");

                    b.Property<int>("CableColor")
                        .HasColumnType("integer");

                    b.Property<int>("Contours")
                        .HasColumnType("integer");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("Extensions1m")
                        .HasColumnType("integer");

                    b.Property<int>("Extensions3m")
                        .HasColumnType("integer");

                    b.Property<int>("GlowMode")
                        .HasColumnType("integer");

                    b.Property<int>("GlowShade")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("OrderObjectId")
                        .HasColumnType("integer");

                    b.Property<int>("PowerUnits")
                        .HasColumnType("integer");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<int>("Surface")
                        .HasColumnType("integer");

                    b.Property<int>("Tees")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderObjectId");

                    b.ToTable("Curtains");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.ElectricShield", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("OrderObjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderObjectId");

                    b.ToTable("ElectricShields");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.Fringe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Bracing")
                        .HasColumnType("integer");

                    b.Property<int>("CableColor")
                        .HasColumnType("integer");

                    b.Property<int>("Contours")
                        .HasColumnType("integer");

                    b.Property<int>("ExtenderCount")
                        .HasColumnType("integer");

                    b.Property<int>("Extensions10m")
                        .HasColumnType("integer");

                    b.Property<int>("Extensions1m")
                        .HasColumnType("integer");

                    b.Property<int>("Extensions3m")
                        .HasColumnType("integer");

                    b.Property<int>("Extensions5m")
                        .HasColumnType("integer");

                    b.Property<int>("GlowMode")
                        .HasColumnType("integer");

                    b.Property<int>("GlowShade")
                        .HasColumnType("integer");

                    b.Property<int>("Led")
                        .HasColumnType("integer");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<int>("Multiplicity")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("OrderObjectId")
                        .HasColumnType("integer");

                    b.Property<int>("PowerUnits")
                        .HasColumnType("integer");

                    b.Property<int?>("Surface")
                        .HasColumnType("integer");

                    b.Property<int>("TeeCount")
                        .HasColumnType("integer");

                    b.Property<int>("Tees")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderObjectId");

                    b.ToTable("Fringes");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.Montage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AutotowerByHours")
                        .HasColumnType("integer");

                    b.Property<int>("AutotowerMobileKm")
                        .HasColumnType("integer");

                    b.Property<int>("Autotower_16_20m")
                        .HasColumnType("integer");

                    b.Property<int>("Autotower_22_24m")
                        .HasColumnType("integer");

                    b.Property<int>("Autotower_26_36m")
                        .HasColumnType("integer");

                    b.Property<int>("Climber")
                        .HasColumnType("integer");

                    b.Property<int>("MontageFringe")
                        .HasColumnType("integer");

                    b.Property<int>("MontageNeon")
                        .HasColumnType("integer");

                    b.Property<int>("MontageThread")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("OrderObjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderObjectId");

                    b.ToTable("Montages");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.Neon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Contours")
                        .HasColumnType("integer");

                    b.Property<int>("FlexibleConnector")
                        .HasColumnType("integer");

                    b.Property<int>("GlowShade")
                        .HasColumnType("integer");

                    b.Property<bool>("IsScreeds_200mm")
                        .HasColumnType("boolean");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<int>("Needles")
                        .HasColumnType("integer");

                    b.Property<int?>("NoRalLength")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("OrderObjectId")
                        .HasColumnType("integer");

                    b.Property<bool>("Painting")
                        .HasColumnType("boolean");

                    b.Property<int>("Plugs")
                        .HasColumnType("integer");

                    b.Property<int>("PowerUnits")
                        .HasColumnType("integer");

                    b.Property<string>("Ral")
                        .HasColumnType("text");

                    b.Property<int?>("RalLength")
                        .HasColumnType("integer");

                    b.Property<int>("Thickness")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderObjectId");

                    b.ToTable("Neons");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.ObjectFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FileEntityId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("OrderObjectId")
                        .HasColumnType("integer");

                    b.Property<int>("TypeEnum")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FileEntityId")
                        .IsUnique();

                    b.HasIndex("OrderObjectId");

                    b.ToTable("ObjectFiles");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.PvsCable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CableColor")
                        .HasColumnType("integer");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("OrderObjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderObjectId");

                    b.ToTable("PvsCables");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.RelaysSwitches", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AstroRele")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("OrderObjectId")
                        .HasColumnType("integer");

                    b.Property<int>("PhotoRele")
                        .HasColumnType("integer");

                    b.Property<int>("Simple_1")
                        .HasColumnType("integer");

                    b.Property<int>("Simple_2")
                        .HasColumnType("integer");

                    b.Property<int>("WirelessWifi_1")
                        .HasColumnType("integer");

                    b.Property<int>("WirelessWifi_2")
                        .HasColumnType("integer");

                    b.Property<int>("WirelessWifi_3")
                        .HasColumnType("integer");

                    b.Property<int>("Wireless_1")
                        .HasColumnType("integer");

                    b.Property<int>("Wireless_2")
                        .HasColumnType("integer");

                    b.Property<int>("Wireless_3")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderObjectId");

                    b.ToTable("RelaysSwitches");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.Rope", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Contours")
                        .HasColumnType("integer");

                    b.Property<int>("DuplexClamps")
                        .HasColumnType("integer");

                    b.Property<int>("Lanyards")
                        .HasColumnType("integer");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("OrderObjectId")
                        .HasColumnType("integer");

                    b.Property<int>("Surface")
                        .HasColumnType("integer");

                    b.Property<int>("Thickness")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderObjectId");

                    b.ToTable("Ropes");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.Screeds_200", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Color")
                        .HasColumnType("integer");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("OrderObjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderObjectId");

                    b.ToTable("Screeds_200s");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.Screeds_480_500", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Color")
                        .HasColumnType("integer");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("OrderObjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderObjectId");

                    b.ToTable("Screeds_480_500s");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.SolderBox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Color")
                        .HasColumnType("integer");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("OrderObjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderObjectId");

                    b.ToTable("SolderBoxes");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.Thread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Bracing")
                        .HasColumnType("integer");

                    b.Property<int>("CableColor")
                        .HasColumnType("integer");

                    b.Property<int>("Contours")
                        .HasColumnType("integer");

                    b.Property<int>("Extensions10m")
                        .HasColumnType("integer");

                    b.Property<int>("Extensions1m")
                        .HasColumnType("integer");

                    b.Property<int>("Extensions3m")
                        .HasColumnType("integer");

                    b.Property<int>("Extensions5m")
                        .HasColumnType("integer");

                    b.Property<int>("GlowMode")
                        .HasColumnType("integer");

                    b.Property<int>("GlowShade")
                        .HasColumnType("integer");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("OrderObjectId")
                        .HasColumnType("integer");

                    b.Property<int>("PowerUnits")
                        .HasColumnType("integer");

                    b.Property<int>("ScreedsType")
                        .HasColumnType("integer");

                    b.Property<int>("Surface")
                        .HasColumnType("integer");

                    b.Property<int>("Tees")
                        .HasColumnType("integer");

                    b.Property<int?>("TreeHeight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderObjectId");

                    b.ToTable("Threads");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.Vagi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("Model")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("OrderObjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderObjectId");

                    b.ToTable("Vagies");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.Work", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FileEntityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FileEntityId")
                        .IsUnique();

                    b.ToTable("Works");
                });

            modelBuilder.Entity("GarlandHouse.DataModel.Entity.OrderObject", b =>
                {
                    b.HasOne("GarlandHouse.DataModel.Entity.Version", "Version")
                        .WithMany("Objects")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("GarlandHouse.DataModel.Entity.UserOrder", b =>
                {
                    b.HasOne("GarlandHouse.DataModel.Entity.Order", "Order")
                        .WithMany("UserOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GarlandHouse.DataModel.Entity.User", "User")
                        .WithMany("UserOrders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GarlandHouse.DataModel.Entity.Version", b =>
                {
                    b.HasOne("GarlandHouse.DataModel.Entity.Order", "BaseOrder")
                        .WithMany("Versions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseOrder");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.Comment", b =>
                {
                    b.HasOne("GarlandHouse.DataModel.Entity.Order", "Order")
                        .WithMany("Comments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GarlandHouse.DataModel.Entity.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.BeltLight", b =>
                {
                    b.HasOne("GarlandHouse.DataModel.Entity.OrderObject", "OrderObject")
                        .WithMany("BeltLights")
                        .HasForeignKey("OrderObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderObject");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.BoxPvsCabel", b =>
                {
                    b.HasOne("GarlandHouse.DataModel.Entity.OrderObject", "OrderObject")
                        .WithMany("BoxPvsCabels")
                        .HasForeignKey("OrderObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderObject");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.Corrugation", b =>
                {
                    b.HasOne("GarlandHouse.DataModel.Entity.OrderObject", "OrderObject")
                        .WithMany("Corrugations")
                        .HasForeignKey("OrderObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderObject");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.Curtain", b =>
                {
                    b.HasOne("GarlandHouse.DataModel.Entity.OrderObject", "OrderObject")
                        .WithMany("Curtains")
                        .HasForeignKey("OrderObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderObject");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.ElectricShield", b =>
                {
                    b.HasOne("GarlandHouse.DataModel.Entity.OrderObject", "OrderObject")
                        .WithMany("ElectricShields")
                        .HasForeignKey("OrderObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderObject");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.Fringe", b =>
                {
                    b.HasOne("GarlandHouse.DataModel.Entity.OrderObject", "OrderObject")
                        .WithMany("Fringes")
                        .HasForeignKey("OrderObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderObject");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.Montage", b =>
                {
                    b.HasOne("GarlandHouse.DataModel.Entity.OrderObject", "OrderObject")
                        .WithMany("Montages")
                        .HasForeignKey("OrderObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderObject");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.Neon", b =>
                {
                    b.HasOne("GarlandHouse.DataModel.Entity.OrderObject", "OrderObject")
                        .WithMany("Neons")
                        .HasForeignKey("OrderObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderObject");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.ObjectFile", b =>
                {
                    b.HasOne("GarlandHouse.DataModel.Entity.FileEntity", "FileEntity")
                        .WithOne()
                        .HasForeignKey("HouseGarland.DataModel.Entity.ObjectItems.ObjectFile", "FileEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GarlandHouse.DataModel.Entity.OrderObject", "OrderObject")
                        .WithMany("ObjectFiles")
                        .HasForeignKey("OrderObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileEntity");

                    b.Navigation("OrderObject");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.PvsCable", b =>
                {
                    b.HasOne("GarlandHouse.DataModel.Entity.OrderObject", "OrderObject")
                        .WithMany("PvsCables")
                        .HasForeignKey("OrderObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderObject");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.RelaysSwitches", b =>
                {
                    b.HasOne("GarlandHouse.DataModel.Entity.OrderObject", "OrderObject")
                        .WithMany("RelaysSwitches")
                        .HasForeignKey("OrderObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderObject");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.Rope", b =>
                {
                    b.HasOne("GarlandHouse.DataModel.Entity.OrderObject", "OrderObject")
                        .WithMany("Ropes")
                        .HasForeignKey("OrderObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderObject");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.Screeds_200", b =>
                {
                    b.HasOne("GarlandHouse.DataModel.Entity.OrderObject", "OrderObject")
                        .WithMany("Screeds_200")
                        .HasForeignKey("OrderObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderObject");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.Screeds_480_500", b =>
                {
                    b.HasOne("GarlandHouse.DataModel.Entity.OrderObject", "OrderObject")
                        .WithMany("Screeds_480_500")
                        .HasForeignKey("OrderObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderObject");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.SolderBox", b =>
                {
                    b.HasOne("GarlandHouse.DataModel.Entity.OrderObject", "OrderObject")
                        .WithMany("SolderBoxes")
                        .HasForeignKey("OrderObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderObject");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.Thread", b =>
                {
                    b.HasOne("GarlandHouse.DataModel.Entity.OrderObject", "OrderObject")
                        .WithMany("Threads")
                        .HasForeignKey("OrderObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderObject");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.ObjectItems.Vagi", b =>
                {
                    b.HasOne("GarlandHouse.DataModel.Entity.OrderObject", "OrderObject")
                        .WithMany("Vagies")
                        .HasForeignKey("OrderObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderObject");
                });

            modelBuilder.Entity("HouseGarland.DataModel.Entity.Work", b =>
                {
                    b.HasOne("GarlandHouse.DataModel.Entity.FileEntity", "FileEntity")
                        .WithOne()
                        .HasForeignKey("HouseGarland.DataModel.Entity.Work", "FileEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileEntity");
                });

            modelBuilder.Entity("GarlandHouse.DataModel.Entity.Order", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("UserOrders");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("GarlandHouse.DataModel.Entity.OrderObject", b =>
                {
                    b.Navigation("BeltLights");

                    b.Navigation("BoxPvsCabels");

                    b.Navigation("Corrugations");

                    b.Navigation("Curtains");

                    b.Navigation("ElectricShields");

                    b.Navigation("Fringes");

                    b.Navigation("Montages");

                    b.Navigation("Neons");

                    b.Navigation("ObjectFiles");

                    b.Navigation("PvsCables");

                    b.Navigation("RelaysSwitches");

                    b.Navigation("Ropes");

                    b.Navigation("Screeds_200");

                    b.Navigation("Screeds_480_500");

                    b.Navigation("SolderBoxes");

                    b.Navigation("Threads");

                    b.Navigation("Vagies");
                });

            modelBuilder.Entity("GarlandHouse.DataModel.Entity.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("UserOrders");
                });

            modelBuilder.Entity("GarlandHouse.DataModel.Entity.Version", b =>
                {
                    b.Navigation("Objects");
                });
#pragma warning restore 612, 618
        }
    }
}
