version: "3.4"

volumes:
  postgres-data:

services:
  housegarland.api:
    build:
      context: ./HouseGarland
      dockerfile: HouseGarland.API/Dockerfile
    container_name: housegarland.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    volumes:
      - ./HouseGarland/uploads:/app/uploads
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    restart: always

  postgres-db:
    container_name: housegarland.postgres-db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: GarlandHouse
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  garland-house-frontend:
    build:
      context: ./garland-house-frontend
      dockerfile: Dockerfile
      target: production
    container_name: garland-house-frontend
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - housegarland.api
    restart: always
    command: npm start
